package com.aideveloper.core;

public class JavaTemplate implements LanguageTemplate {
    @Override
    public String generate(String requirements) {
        return "public class GeneratedClass {\n" +
                "    // Auto-generated by AI Developer\n" +
                "    // Requirements: " + requirements + "\n" +
                "    \n" +
                "    public static void main(String[] args) {\n" +
                "        System.out.println(\"AI Generated Java Code\");\n" +
                "    }\n" +
                "}";
    }

    @Override
    public String getName() {
        return "Java";
    }
}